#!/usr/bin/env python3
"""
Explore what StableHLO operations are generated by pmap, shard_map, and collective ops.
"""

import jax
import jax.numpy as jnp
from jax import lax
import numpy as np


# Test 1: Simple pmap
print("="*80)
print("TEST 1: Simple pmap")
print("="*80)

def f_pmap(x):
    return x * 2.0

x = jnp.array([[1.0, 2.0], [3.0, 4.0]])
f_pmapped = jax.pmap(f_pmap)

try:
    lowered = f_pmapped.lower(x)
    mlir_module = lowered.compiler_ir(dialect='stablehlo')
    print(mlir_module)
except Exception as e:
    print(f"Error: {e}")


# Test 2: pmap with psum
print("\n" + "="*80)
print("TEST 2: pmap with lax.psum")
print("="*80)

def f_psum(x):
    return lax.psum(x, axis_name='i')

x = jnp.array([[1.0, 2.0], [3.0, 4.0]])
f_pmapped = jax.pmap(f_psum, axis_name='i')

try:
    lowered = f_pmapped.lower(x)
    mlir_module = lowered.compiler_ir(dialect='stablehlo')
    print(mlir_module)
except Exception as e:
    print(f"Error: {e}")


# Test 3: pmap with all_gather
print("\n" + "="*80)
print("TEST 3: pmap with lax.all_gather")
print("="*80)

def f_all_gather(x):
    return lax.all_gather(x, axis_name='i')

x = jnp.array([[1.0, 2.0], [3.0, 4.0]])
f_pmapped = jax.pmap(f_all_gather, axis_name='i')

try:
    lowered = f_pmapped.lower(x)
    mlir_module = lowered.compiler_ir(dialect='stablehlo')
    print(mlir_module)
except Exception as e:
    print(f"Error: {e}")


# Test 4: Regular function (no pmap)
print("\n" + "="*80)
print("TEST 4: Regular function (no pmap)")
print("="*80)

def f_regular(x):
    return jnp.sum(x) * x

x = jnp.array([1.0, 2.0, 3.0])
lowered = jax.jit(f_regular).lower(x)
mlir_module = lowered.compiler_ir(dialect='stablehlo')
print(mlir_module)
